'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald, Roboto } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";
import toast from "react-hot-toast";
import { api } from "../../utils/apiUtils";
import { useRouter } from "next/navigation";
import { StoreProvider } from "../../redux/StoreProvider";


const oswald = Oswald({ subsets: ['latin'], weight: ['200','400','700'] })
// const roboto = Roboto({ subsets: ['latin'], weight: ['300','400','500','700'] })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // always check if the current refresh token has expired or not
  // if it has expired then route to auth page
  // then go back to usual routing
  const router = useRouter()

  useEffect(() => {
    verifyRefreshToken()
  }, [])

  const verifyRefreshToken = async () => {
    try{
      const response = await api.get('/auth/verify-refresh-token')
      if(response.status !== 200)
      {
        router.push('/auth')
      }
    }
    catch(err){
      toast.error(`Could not validate refresh token`)
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${oswald.className} antialiased`}
      >
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
