version: "3.8"

services:
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - transcoder-network
  #   volumes:
  #     - transcoder_redis_data:/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myTranscoderDB
      PGDATA: /var/lib/postgresql/newData
    networks:
      - transcoder-network
    volumes:
      - transcoder_postgres_data:/var/lib/postgresql/newData
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myusername -d myTranscoderDB"]
      interval: 5s
      timeout: 5s
      retries: 5
    
volumes:
  # transcoder_redis_data:
  transcoder_postgres_data:

networks:
  transcoder-network:
    name: transcoder-network
    driver: bridge